//! Emit the C# side of the contract.
//!
//! A closed record hierarchy with a `Match` method, rather than a language-level
//! union. The representation is the generator's to choose, which is what makes
//! the .NET version question a flag rather than a rewrite: when union types
//! reach a supported channel, this emitter changes and no hand-written line
//! does.

use std::fmt::Write as _;

use crate::ast::{Schema, Union, csharp_type, pascal};

/// Generate a C# file for one schema file.
#[must_use]
pub fn emit(schema: &Schema, stem: &str) -> String {
    let mut out = String::new();
    header(&mut out, stem);
    for union in &schema.union {
        union_block(&mut out, union);
    }
    out
}

/// The file preamble: provenance, nullability, namespace.
fn header(out: &mut String, stem: &str) {
    let _ = writeln!(out, "// <auto-generated />");
    let _ = writeln!(
        out,
        "// Generated from contract/schema/{stem}.toml. Do not edit."
    );
    let _ = writeln!(out, "//");
    let _ = writeln!(
        out,
        "// Regenerate with `just codegen`. Continuous integration regenerates"
    );
    let _ = writeln!(
        out,
        "// and compares, so a hand edit fails the build rather than surviving"
    );
    let _ = writeln!(out, "// until it contradicts the other language.");
    let _ = writeln!(out, "#nullable enable");
    let _ = writeln!(out);
    let _ = writeln!(out, "using System;");
    let _ = writeln!(out);
    let _ = writeln!(out, "namespace AfkAgent.Contract;");
    let _ = writeln!(out);
}

/// One union: the abstract base, its variants, and the exhaustive `Match`.
fn union_block(out: &mut String, union: &Union) {
    if !union.doc.is_empty() {
        let _ = writeln!(out, "/// <summary>{}</summary>", union.doc);
    }
    let _ = writeln!(out, "public abstract partial record {}", union.name);
    let _ = writeln!(out, "{{");
    let _ = writeln!(
        out,
        "    // Private constructor: the hierarchy is closed, so a `Match` that"
    );
    let _ = writeln!(out, "    // compiles is a `Match` that handles every case.");
    let _ = writeln!(out, "    private {}() {{ }}", union.name);
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "    /// <summary>The wire tag for this value.</summary>"
    );
    let _ = writeln!(out, "    public abstract ushort Tag {{ get; }}");
    let _ = writeln!(out);

    for variant in &union.variant {
        if !variant.doc.is_empty() {
            let _ = writeln!(out, "    /// <summary>{}</summary>", variant.doc);
        }
        let params: Vec<String> = variant
            .fields
            .iter()
            .map(|field| {
                let kind = csharp_type(&field.kind).unwrap_or("object");
                format!("{kind} {}", pascal(&field.name))
            })
            .collect();
        let _ = writeln!(
            out,
            "    public sealed partial record {}({}) : {}",
            variant.name,
            params.join(", "),
            union.name
        );
        let _ = writeln!(out, "    {{");
        let _ = writeln!(out, "        /// <inheritdoc />");
        let _ = writeln!(
            out,
            "        public override ushort Tag => {};",
            variant.tag
        );
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out);
    }

    let arms: Vec<String> = union
        .variant
        .iter()
        .map(|variant| format!("Func<{}, T> {}", variant.name, camel(&variant.name)))
        .collect();
    let _ = writeln!(
        out,
        "    /// <summary>Handle every case. Adding a variant breaks every caller, deliberately.</summary>"
    );
    let _ = writeln!(
        out,
        "    public T Match<T>({}) => this switch",
        arms.join(", ")
    );
    let _ = writeln!(out, "    {{");
    for variant in &union.variant {
        let _ = writeln!(
            out,
            "        {} value => {}(value),",
            variant.name,
            camel(&variant.name)
        );
    }
    let _ = writeln!(out, "        _ => throw new InvalidOperationException(");
    let _ = writeln!(
        out,
        "            \"unreachable: the hierarchy is closed\"),"
    );
    let _ = writeln!(out, "    }};");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

/// A variant name as a C# parameter name.
fn camel(name: &str) -> String {
    let pascal = pascal(name);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => pascal,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> Schema {
        toml::from_str(
            "schema_version = 1\n\
             [[union]]\n\
             name = \"Event\"\n\
             [[union.variant]]\n\
             name = \"SessionState\"\n\
             tag = 1\n\
             fields = [{ name = \"state\", type = \"u8\" }, { name = \"reason\", type = \"string\" }]\n",
        )
        .expect("the fixture parses")
    }

    #[test]
    fn the_hierarchy_is_closed() {
        // The private constructor is what makes Match exhaustive. Without it a
        // consumer can add a variant from outside and every switch is wrong.
        let code = emit(&fixture(), "events");
        assert!(code.contains("private Event() { }"));
        assert!(code.contains("public sealed partial record SessionState"));
    }

    #[test]
    fn the_wire_tag_is_carried_on_the_type() {
        let code = emit(&fixture(), "events");
        assert!(code.contains("public override ushort Tag => 1;"));
    }

    #[test]
    fn schema_types_become_csharp_types() {
        let code = emit(&fixture(), "events");
        assert!(code.contains("SessionState(byte State, string Reason)"));
    }

    #[test]
    fn the_match_parameter_is_named_after_its_variant() {
        let code = emit(&fixture(), "events");
        assert!(code.contains("Func<SessionState, T> sessionState"));
        assert!(code.contains("SessionState value => sessionState(value),"));
    }
}
