#!/usr/bin/env python3
"""Check that every generated page matches what the generator would produce.

`docs/reference/index.md` says generated pages are regenerated by continuous
integration and fail when the committed copy differs. That is the mechanism
that stops a reference page describing code it no longer matches — the kind of
drift nobody notices, because a stale page reads exactly like a fresh one.

Each page declares its generator in front matter. This runs it into a temporary
location and compares. A difference prints the first few differing lines and
names the command that fixes it, because "the generated file is stale" without
the command is a puzzle rather than an instruction.

Exit code 0 when every generated page is current, 1 otherwise.
"""

from __future__ import annotations

import difflib
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(os.environ.get("CLAUDE_PROJECT_DIR", ".")).resolve()

# Generated page -> the command that produces it, with {out} for the target.
# Kept here rather than inferred from front matter, because the command is a
# fact about the build and belongs where a person can read it.
GENERATORS: dict[str, list[str]] = {
    "docs/reference/traceability.md": [
        sys.executable,
        "tools/lint_requirements.py",
        "docs",
        "--source",
        "crates",
        "src",
        "tests",
        "tools",
        "--emit",
        "{out}",
        "--emit-as",
        "docs/reference/traceability.md",
    ],
}


def annotate(message: str, *, file: str | None = None) -> None:
    if os.environ.get("GITHUB_ACTIONS"):
        location = f" file={file}" if file else ""
        print(f"::error{location}::{message}")
    else:
        prefix = f"{file}: " if file else ""
        print(f"{prefix}{message}", file=sys.stderr)


def main() -> int:
    stale = 0
    checked = 0

    with tempfile.TemporaryDirectory() as tmp:
        for page, command in GENERATORS.items():
            target = ROOT / page
            if not target.is_file():
                annotate(f"{page} is declared generated but does not exist")
                stale += 1
                continue

            out = Path(tmp) / Path(page).name
            argv = [arg.format(out=str(out)) for arg in command]
            result = subprocess.run(
                argv,
                cwd=ROOT,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
            )
            if not out.is_file():
                annotate(
                    f"the generator for {page} produced nothing "
                    f"(exit {result.returncode}): {result.stderr.strip()[-400:]}",
                    file=page,
                )
                stale += 1
                continue

            checked += 1
            committed = target.read_text(encoding="utf-8").splitlines()
            fresh = out.read_text(encoding="utf-8").splitlines()
            if committed == fresh:
                continue

            diff = list(
                difflib.unified_diff(committed, fresh, "committed", "regenerated", lineterm="", n=1)
            )
            annotate(
                f"{page} does not match what its generator produces. "
                "Regenerate it and commit the result.",
                file=page,
            )
            for line in diff[:20]:
                print("    " + line, file=sys.stderr)
            if len(diff) > 20:
                print(f"    … {len(diff) - 20} more lines", file=sys.stderr)
            print(
                "    fix: " + " ".join(a.format(out=page) for a in command[1:]),
                file=sys.stderr,
            )
            stale += 1

    if stale:
        print(f"{stale} generated page(s) out of date", file=sys.stderr)
        return 1

    print(f"generated pages: {checked} current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
